apiVersion: v1
kind: Namespace
metadata:
  name:  ns-petstore
  labels:
    name: ns-petstore

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstoreorder
  namespace: ns-petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstoreorder
  template:
    metadata:
      labels:
        app: petstoreorder
    spec:
      containers:
      - name: petstoreorder
        image: contregpetstore.azurecr.io/petstoreorderservice
        imagePullPolicy: IfNotPresent
        env:
        - name: PETSTOREORDERSERVICE_SERVER_PORT
          value: "80"
        - name: PETSTOREPRODUCTSERVICE_URL
          value: http://petstoreproduct-service
        resources:
          requests:
              cpu: 250m
              memory: 500Mi
          limits:
            memory: "900Mi"
            cpu: "700m"
        readinessProbe:
          httpGet:
            path: /petstoreorderservice/v2/store/info
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: petstoreorder-service
  namespace: ns-petstore
spec:
  selector:
    app: petstoreorder
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
